
import { Roboto } from 'next/font/google'
import "./globals.css";



const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
})

export const metadata = {
  title: "My Nextjs App-1",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning >
      <body className={roboto.className} >
        {children}
      </body>
    </html>
  );
}
